version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
            curl -fL https://getcli.jfrog.io | sh
            ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD --interactive=false
#       - restore_cache:
#           keys:
#             - v1-{{ .Branch }}
#           paths:
#             - /caches/app.tar
#       - run:
#           name: Load Docker image layer cache
#           command: |
#             set +o pipefail
#             docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
 #           docker build --cache-from=app -t app .
            docker build --rm=false -t $ARTIFACTORY_DOCKER_REPOSITORY/node-version:$CIRCLE_BUILD_NUM .
#       - run:
#           name: Save Docker image layer cache
#           command: |
#             mkdir -p /caches
#             docker save -o /caches/app.tar app
#test:

#       - run:
#            name: Build application Docker image
#                 command: |
#        #           docker build --cache-from=app -t app .
#                   docker run -d -p 3000:3000 $ARTIFACTORY_DOCKER_REPOSITORY/node-version:$CIRCLE_BUILD_NUM; sleep 10
#                   curl --retry 10 --retry-delay 5 -v http://localhost:3000

      - run:
          name: Run tests
          command: |
            docker run -d -p 3000:3000 $ARTIFACTORY_DOCKER_REPOSITORY/node-version:$CIRCLE_BUILD_NUM; sleep 10
            curl --retry 10 --retry-delay 5 -v http://localhost:3000
      - deploy:
          name: Push application Docker image
            command: |
              docker login -e $ARTIFACTORY_EMAIL -u $ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD $ARTIFACTORY_DOCKER_REPOSITORY
              ./jfrog rt dp $ARTIFACTORY_DOCKER_REPOSITORY/node-version:$CIRCLE_BUILD_NUM docker-dev --build-name=circleci-docker-artifactory --build-number=$CIRCLE_BUILD_NUM
              ./jfrog rt bce circleci-docker-artifactory $CIRCLE_BUILD_NUM
              ./jfrog rt bp circleci-docker-artifactory $CIRCLE_BUILD_NUM
              
#           command: |
#             if [ "${CIRCLE_BRANCH}" == "master" ]; then
#               login="$(aws ecr get-login)"
#               ${login}
#               docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
#               docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
#             fi
